#!/usr/bin/env bash

SRC_DIR=$1
SCRIPT_INPUT='/tmp/input'
cat > $SCRIPT_INPUT <&0 # STDIN params

TOKEN=$(jq -r '.source.token // ""' < $SCRIPT_INPUT)

cd $SRC_DIR

find . -type f -print0 | xargs -0 -I file mv file .  1>&2
anaconda --token ${TOKEN} upload --force *.tar.bz2  1>&2

if [ $? -eq 0 ]; then
    echo "{ \"version\": { \"ref\": \"\"} }"
fi

exit $?
