#!/usr/bin/env bash

SRC_DIR=$1
SCRIPT_INPUT='/tmp/input'
cat > $SCRIPT_INPUT <&0 # STDIN params

TOKEN=$(jq -r '.source.token // ""' < $SCRIPT_INPUT)

shopt -s globstar 1>&2
anaconda --token ${TOKEN} upload $(find . -type f -iname *.tar.bz2)

if [ $? -eq 0 ]; then
    echo "{ \"version\": { \"ref\": \"\"} }"
fi

exit $?
